```{r}
load("raw_valid.Rdata")
load("paintings_test.Rdata")
load("paintings_train.Rdata")
load("raw_test.Rdata")
load("paintings_validation.Rdata")
clean.new = function(df, NA.omit=F){
   df = df %>% 
     select(-c(sale, price, count, subject, winningbidder, authorstandard, authorstyle, author, Height_in, Width_in, Surface_Rect, Diam_in, winningbiddertype, Surface_Rnd,material,materialCat, Interm)) %>%
     mutate(lot = as.numeric(lot)) %>%
     mutate(mat=as.character(mat))%>%
     mutate(mat_recode = ifelse(mat %in% c("a", "bc", "c"), "metal",
                          ifelse(mat %in% c("al", "ar", "m"), "other",
                                ifelse(mat %in% c("co", "bt", "t"), "canvas",
                                       ifelse(mat %in% c("p", "ca"), "paper",
                                              ifelse(mat %in% c("b"), "wood",
                                                     ifelse(mat %in% c("o", "e", "v"), "other",
                                                            ifelse(mat %in% c("n/a", ""), "na",
                                                                   "other")))))))) %>%
     mutate(school_pntg=as.character(school_pntg))%>%
     mutate(school_pntg_recode = ifelse(school_pntg %in% c("A", "G", "S"), "other",school_pntg)) %>%
     mutate(origin_cat=ifelse(origin_cat %in% c("X","S"),"O",origin_cat))%>%
     mutate(SurfaceNA = ifelse(is.na(df$Surface), 1, 0))%>%
     mutate(nfigures=as.numeric(nfigures))%>%
     mutate(Surface=log(Surface+1))%>%
     mutate(endbuyer=as.character(endbuyer))%>%
     mutate(endbuyer = ifelse(endbuyer == "", "NA", endbuyer)) %>% 
     mutate(Shape=as.character(Shape))%>%
   mutate(shape_recode = ifelse(Shape == "", "Other",
                               ifelse(Shape == "ovale", "oval",
                                      ifelse(Shape == "ronde", "round",
                                             ifelse(Shape %in% c("octogon","octagon"), "Other", Shape)))))%>%
     select(-c(mat,school_pntg, Shape))%>%
     mutate(type_intermed=as.character(type_intermed))%>%
     mutate(type_intermed=ifelse(type_intermed == "EB","B",type_intermed))
   
   
   factornames=colnames(df)[!colnames(df) %in% c("logprice","lot","position","Surface","nfigures")] 
   
   
   df[factornames] = lapply(df[factornames], factor)

   df$Surface[is.na(df$Surface)] = 0
  
  
   if(NA.omit==T){
      df = na.omit(df)
   }


   #df=df[vapply(df, function(x) length(unique(x)) > 1, logical(1L))]
   
  return(df) 
}

rmse <- function(y, ypred) {
rmse <- sqrt(mean((y - ypred)^2))
return(rmse)
}

train = clean.new(paintings_train) %>% select(-lot)
test = clean.new(paintings_test)%>% select(-lot)
test.true = clean.new(test.raw) %>% select(-lot)
valid.true = clean.new(valid) %>% select(-lot)
validation = clean.new(paintings_validation)%>% select(-lot)
```

```{r}
#lasso
library(glmnet)
x = model.matrix(logprice~., train)
y= train$logprice
grid = 10^(seq(10,-2, length=100))

lasso.mod= glmnet(x,y,alpha=1, lambda=grid)
#plot(lasso.mod)
set.seed(1)

cv.out = cv.glmnet(x,y, alpha=1)
#plot(cv.out)
bestlam=cv.out$lambda.min
lasso.mod2 = glmnet(x,y,alpha=1, lambda=bestlam)

test=test%>%
  mutate(logprice=1)
x.test = model.matrix(logprice~.,test)
pred=predict(lasso.mod2, x.test)

pred=exp(pred)


test.rmse = rmse(exp(test.true$logprice), as.numeric(pred))

###############


train1=train%>%
  mutate(logprice=1)
x.test = model.matrix(logprice~.,train1)
pred=predict(lasso.mod2, x.test)

pred=exp(pred)

train.rmse = rmse(exp(as.numeric(paintings_train$logprice)), as.numeric(pred))


#############




validation=validation%>%
  mutate(logprice=1)
x.test = model.matrix(logprice~.,validation)
pred=predict(lasso.mod2, x.test)

pred=exp(pred)


valid.rmse = rmse(exp(as.numeric(valid.true$logprice)), as.numeric(pred))

```




```{r}
library(caret)

cv.ctrl <- trainControl(method = "repeatedcv", repeats = 3,number = 3,
                        classProbs = TRUE,
                        allowParallel=T)

xgb.grid <- expand.grid(nrounds = 100,
                        eta = seq(0.01, 0.21, by = 0.05),
                        lambda = seq(0.1, 1, by = 0.1),
                        alpha = 1)


set.seed(45)
xgb_tune <-train(logprice~.,
                 data=train,
                 trControl = cv.ctrl,
                 method="xgbLinear",
                 tuneGrid=xgb.grid,
                 gamma = 1,
                 nthread = 8
    )

predictions.test = predict(xgb_tune, newdata = test) %>% exp()
predictions.valid = predict(xgb_tune, newdata = validation) %>% exp()

predictions.train = predict(xgb_tune) %>% exp()

train.rmse1 = rmse(exp(as.numeric(paintings_train$logprice)), as.numeric(predictions.train))


test.rmse1 = rmse(exp(test.true$logprice), as.numeric(predictions.test))

valid.rmse1 = rmse(exp(as.numeric(valid.true$logprice)), as.numeric(predictions.valid))

```


```{r}
# model1 = lm(logprice~Surface + dealer + endbuyer + diff_origin + type_intermed + engraved + mat_recode+school_pntg_recode+paired + lrgfont + lands_sc + othgenre + discauth + othartist+still_life,
#     data = train)
# 
# pred1 = predict(model1)
# 
# pred3 = predict(model1, newdata = validation)
# 
# 
# valid.rmse.before = rmse(exp(as.numeric(valid.true$logprice)), as.numeric(pred3))
# 
# 
# train.rmse.before = rmse(exp(as.numeric(paintings_train$logprice)), as.numeric(pred1))
```



```{r}
cv.ctrl2 <- trainControl(method = "repeatedcv", repeats = 3,number = 3,
                        classProbs = TRUE,
                        allowParallel=T)

xgb.grid2 <- expand.grid(nrounds = 100,
                        eta = seq(0.01, 0.21, by = 0.05),
                        lambda = seq(0.1, 1, by = 0.1),
                        alpha = 1)


set.seed(45)
xgb_tune2 <-train(logprice~.,
                 data=train,
                 trControl = cv.ctrl,
                 method="xgbLinear",
                 tuneGrid=xgb.grid,
                 gamma = 1,
                 nthread = 8,
                 metric = c("RMSE"),
                maximize = FALSE

    )

predictions.test3 = predict(xgb_tune2, newdata = test) %>% exp()
predictions.valid3 = predict(xgb_tune2, newdata = validation) %>% exp()

predictions.train3 = predict(xgb_tune2) %>% exp()



train.rmse2 = rmse(exp(as.numeric(paintings_train$logprice)), as.numeric(predictions.train3))


test.rmse2 = rmse(exp(test.true$logprice), as.numeric(predictions.test3))

valid.rmse2 = rmse(exp(as.numeric(valid.true$logprice)), as.numeric(predictions.valid3))
```


```{r}
model0 = lm(logprice ~ 1+., data = train)

model1 = step(model0, k=2, trace = 1, direction = "forward")

predictions.test4 = predict(model1, newdata = test) %>% exp()
predictions.valid4 = predict(model1, newdata = validation) %>% exp()

predictions.train4 = predict(model1) %>% exp()



train.rmse3 = rmse(exp(as.numeric(paintings_train$logprice)), as.numeric(predictions.train4))


test.rmse3 = rmse(exp(test.true$logprice), as.numeric(predictions.test4))

valid.rmse3 = rmse(exp(as.numeric(valid.true$logprice)), as.numeric(predictions.valid4))
```


```{r}
library(lars)
library(monomvn)
yf = train[,7]
Xf = train[,7]
rbhs = blasso(Xf, yf, case="hs",
theta = 0.1, RJ=FALSE,
thin=10, T=2000,
verb=0)
y.pred = mean(rbhs$mu) +
Xf %*% apply(rbhs$beta, 2, mean)
```



```{r}
library(BAS)
df.bas = bas.lm(logprice~., data=train,
prior="g-prior", a=nrow(train), modelprior=uniform(),
method="MCMC", MCMC.iterations = 200000, thin = 20)

y.test.bma = predict(df.bas, newdata = test, estimator = "BMA", se.fit = TRUE, prediction = FALSE)

y.valid.bma = predict(df.bas, newdata = validation, estimator = "BMA", se.fit = TRUE, prediction = FALSE)

y.train.bma = predict(df.bas,  estimator = "BMA", se.fit = TRUE, prediction = FALSE)

plot(df.bas)


train.rmse4 = rmse(exp(as.numeric(paintings_train$logprice)), exp(as.numeric(y.train.bma$fit)))


test.rmse4 = rmse(exp(test.true$logprice), exp(as.numeric(y.test.bma$fit)))

valid.rmse4 = rmse(exp(as.numeric(valid.true$logprice)), exp(as.numeric(y.valid.bma$fit)))


```


```{r}
df.bas1 = bas.lm(logprice~dealer + year + origin_author + origin_cat +
                  diff_origin + endbuyer + type_intermed + Surface +
                  nfigures + engraved + prevcoll + paired + finished +
                  lrgfont + othgenre + portrait + still_life + discauth +
                  school_pntg_recode + SurfaceNA + shape_recode, data=train,
prior="g-prior", a=nrow(train), modelprior=uniform(),
method="MCMC", MCMC.iterations = 2000000, thin = 20)




y.test.bma1 = predict(df.bas1, newdata = test, estimator = "BMA", se.fit = TRUE, prediction = FALSE)

y.valid.bma1 = predict(df.bas1, newdata = validation, estimator = "BMA", se.fit = TRUE, prediction = FALSE)

y.train.bma1 = predict(df.bas1,  estimator = "BMA", se.fit = TRUE, prediction = FALSE)


train.rmse5 = rmse(exp(as.numeric(paintings_train$logprice)), exp(as.numeric(y.train.bma1$fit)))


test.rmse5 = rmse(exp(test.true$logprice), exp(as.numeric(y.test.bma1$fit)))

valid.rmse5 = rmse(exp(as.numeric(valid.true$logprice)), exp(as.numeric(y.valid.bma1$fit)))


```


```{r}
library(randomForest)



rf.nes = randomForest(logprice ~ dealer + year + origin_author + origin_cat +
                  diff_origin + endbuyer + type_intermed + Surface +
                  nfigures + engraved + prevcoll + paired + finished +
                  lrgfont + othgenre + portrait + still_life + discauth +
                  school_pntg_recode + SurfaceNA + shape_recode, data=train,  importance =TRUE) 

yhat.rf.test= predict(rf.nes ,newdata =test)

yhat.rf.vali= predict(rf.nes ,newdata =validation)

yhat.rf.train= predict(rf.nes)


test.rmse6 = rmse(exp(test.true$logprice), exp(as.numeric(yhat.rf.test)))

valid.rmse6 = rmse(exp(as.numeric(valid.true$logprice)), exp(as.numeric(yhat.rf.vali)))

train.rmse6 = rmse(exp(as.numeric(paintings_train$logprice)), exp(as.numeric(yhat.rf.train)))


```

```{r}
library(randomForest)



rf.nes1 = randomForest(logprice ~ dealer + year + origin_cat + diff_origin + 
    artistliving + endbuyer + type_intermed + Surface + nfigures + 
    engraved + prevcoll + othartist + paired + finished + lrgfont + 
    landsALL + lands_sc + othgenre + portrait + still_life + 
    discauth + mat_recode + school_pntg_recode + SurfaceNA + 
    shape_recode, data = train,  importance =TRUE) 



yhat.rf.test1= predict(rf.nes1 ,newdata =test)

yhat.rf.vali1= predict(rf.nes1,newdata =validation)

yhat.rf.train1= predict(rf.nes1)


test.rmse7 = rmse(exp(test.true$logprice), exp(as.numeric(yhat.rf.test1)))

valid.rmse7 = rmse(exp(as.numeric(valid.true$logprice)), exp(as.numeric(yhat.rf.vali1)))

train.rmse7 = rmse(exp(as.numeric(paintings_train$logprice)), exp(as.numeric(yhat.rf.train1)))
```



```{r}
df.bas2 = bas.lm(logprice ~ dealer + year + origin_cat + diff_origin + 
    artistliving + endbuyer + type_intermed + Surface + nfigures + 
    engraved + prevcoll + othartist + paired + finished + lrgfont + 
    landsALL + lands_sc + othgenre + portrait + still_life + 
    discauth + mat_recode + school_pntg_recode + SurfaceNA + 
    shape_recode, data=train,
prior="g-prior", a=nrow(train), modelprior=uniform(),
method="MCMC", MCMC.iterations = 2000000, thin = 20)




y.test.bma2 = predict(df.bas2, newdata = test, estimator = "BMA", se.fit = TRUE, prediction = FALSE)

y.valid.bma2 = predict(df.bas2, newdata = validation, estimator = "BMA", se.fit = TRUE, prediction = FALSE)

y.train.bma2 = predict(df.bas2,  estimator = "BMA", se.fit = TRUE, prediction = FALSE)


train.rmse8 = rmse(exp(as.numeric(paintings_train$logprice)), exp(as.numeric(y.test.bma2$fit)))


test.rmse8 = rmse(exp(test.true$logprice), exp(as.numeric(y.test.bma2$fit)))

valid.rmse8 = rmse(exp(as.numeric(valid.true$logprice)), exp(as.numeric(y.valid.bma2$fit)))
```


#THE BEST

```{r}
library(BayesTree)
x.train.new=train%>%
  dplyr::select(position,dealer , year , diff_origin ,origin_author, origin_cat, endbuyer , 
    type_intermed , Surface , nfigures , engraved , prevcoll , artistliving,original,othartist,
    paired , finished , lrgfont,  othgenre , portrait , still_life , figures,relig,landsALL,
    discauth , school_pntg_recode , SurfaceNA,lands_sc, singlefig, history,allegory, pastorale,
    other, mat_recode, shape_recode)

y.train.new=train$logprice

x.test.new=test%>%
 dplyr:: select(position,dealer , year , diff_origin ,origin_author, origin_cat, endbuyer , 
    type_intermed , Surface , nfigures , engraved , prevcoll , artistliving,original,othartist,
    paired , finished , lrgfont,  othgenre , portrait , still_life , figures,relig,landsALL,
    discauth , school_pntg_recode , SurfaceNA,lands_sc, singlefig, history,allegory, pastorale,
    other, mat_recode, shape_recode
)

x.test.valid=valid.true%>%
  dplyr::select(position,dealer , year , diff_origin ,origin_author, origin_cat, endbuyer , 
    type_intermed , Surface , nfigures , engraved , prevcoll , artistliving,original,othartist,
    paired , finished , lrgfont,  othgenre , portrait , still_life , figures,relig,landsALL,
    discauth , school_pntg_recode , SurfaceNA,lands_sc, singlefig, history,allegory, pastorale,
    other, mat_recode, shape_recode

)
set.seed(12)
bart.valid=bart(x.train=x.train.new,y.train=y.train.new,x.test=x.test.valid,verbose=FALSE,ndpost = 5000)
set.seed(12)
bart.test=bart(x.train=x.train.new,y.train=y.train.new,x.test=x.test.new,verbose=FALSE,ndpost = 5000)
set.seed(12)
bart.train=bart(x.train=x.train.new,y.train=y.train.new,x.test=x.train.new,verbose=FALSE,ndpost = 5000)


pihat.bart.valid=apply(bart.nes.valid$yhat.test,2,mean)

pihat.bart.test=apply(bart.nes.test$yhat.test,2,mean)

pihat.bart.train=apply(bart.nes.train$yhat.test,2,mean)


y.valid=exp(pihat.bart.valid)

y.test=exp(pihat.bart.test)

y.train=exp(pihat.bart.train)


valid.rmse9=rmse(exp(valid.true$logprice),y.valid)

test.rmse9=rmse(exp(test.true$logprice),y.test)

train.rmse9=rmse(exp(train$logprice),y.train)

ci.test = t(exp(apply(bart.test$yhat.test,2,quantile, c(0.025,0.975))))


predictions = data.frame(exp(pihat.bart.test), ci.test[,1], ci.test[,2])

colnames(predictions) = c("fit", "lwr", "upr")


save(predictions, file = "predict-test.Rdata")
```

```{r}
library(bartMachine)
bart.test=bartMachine(X=x.train.new,y=y.train.new,verbose=FALSE)
ci = calc_prediction_intervals(bart.test, x.test.new,pi_conf = 0.95, num_samples_per_data_point = 10000)
ci = exp(ci)
fit = predict(bart.test, new_data = x.test.new) %>% exp()
fit.valid = predict(bart.test, new_data = x.test.valid)
fit.train = predict(bart.test, new_data = x.train.new)

rmse(exp(fit.train), y.train)
rmse(fit, y.test)
rmse(exp(fit.valid), y.valid)

predictions = cbind(fit, ci) %>% as.data.frame()
colnames(predictions) = c("fit","lwr","upr")
save(predictions, file = "predict-test.Rdata")
```



```{r}
x.train.new=train%>%
  dplyr::select(dealer , year , origin_cat , diff_origin , 
    artistliving , endbuyer , type_intermed , Surface , nfigures , 
    engraved , prevcoll , othartist , paired , finished ,lrgfont , 
    landsALL , lands_sc , othgenre , portrait , still_life , 
    discauth , mat_recode , school_pntg_recode , SurfaceNA , 
    shape_recode)

y.train.new=train$logprice

x.test.new=test%>%
 dplyr:: select(dealer , year , origin_cat , diff_origin , 
    artistliving , endbuyer , type_intermed , Surface , nfigures , 
    engraved , prevcoll , othartist , paired , finished ,lrgfont , 
    landsALL , lands_sc , othgenre , portrait , still_life , 
    discauth , mat_recode , school_pntg_recode , SurfaceNA , 
    shape_recode
)

x.test.valid=valid.true%>%
  dplyr::select(dealer , year , origin_cat , diff_origin , 
    artistliving , endbuyer , type_intermed , Surface , nfigures , 
    engraved , prevcoll , othartist , paired , finished ,lrgfont , 
    landsALL , lands_sc , othgenre , portrait , still_life , 
    discauth , mat_recode , school_pntg_recode , SurfaceNA , 
    shape_recode

)

bart.nes.valid=bart(x.train=x.train.new,y.train=y.train.new,x.test=x.test.valid,verbose=FALSE)

bart.nes.test=bart(x.train=x.train.new,y.train=y.train.new,x.test=x.test.new,verbose=FALSE)

bart.nes.train=bart(x.train=x.train.new,y.train=y.train.new,x.test=x.train.new,verbose=FALSE)


pihat.bart.valid=apply(bart.nes.valid$yhat.test,2,mean)

pihat.bart.test=apply(bart.nes.test$yhat.test,2,mean)

pihat.bart.train=apply(bart.nes.train$yhat.test,2,mean)


y.valid=exp(pihat.bart.valid)

y.test=exp(pihat.bart.test)

y.train=exp(pihat.bart.train)


valid.rmse10=rmse(exp(valid.true$logprice),y.valid)

test.rmse10=rmse(exp(test$logprice),y.test)

train.rmse10=rmse(exp(train$logprice),y.train)
```

